//  Account.swift
//  MySampleApp
//
//
// Copyright 2019 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.21
//

import Foundation
import UIKit
import AWSDynamoDB

class Account: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    @objc var _userId: String?
    @objc var _answer: String?
    @objc var _password: String?
    @objc var _question: String?
    @objc var _fri: Set<String>?
    @objc var _mon: Set<String>?
    @objc var _sat: Set<String>?
    @objc var _sun: Set<String>?
    @objc var _thu: Set<String>?
    @objc var _tue: Set<String>?
    @objc var _wed: Set<String>?
    class func dynamoDBTableName() -> String {
        
        return "csproject-mobilehub-1949109104-Account"
    }
    
    class func hashKeyAttribute() -> String {
        
        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
            "_userId" : "userId",
            "_answer" : "answer",
            "_password" : "password",
            "_question" : "question",
            "_sat" : "sat",
            "_sun" : "sun",
            "_thu" : "thu",
            "_tue" : "tue",
            "_wed" : "wed",
            "_fri" : "fri",
            "_mon" : "mon",
        ]
    }
}
