# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'PurdueClass'

use_frameworks!
target 'PurdueClass' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks


  # Pods for PurdueClass
  	pod 'Moya', '~> 12.0'
	pod 'AWSAutoScaling'
     pod 'AWSCloudWatch'
     pod 'AWSCognito'
     pod 'AWSCognitoIdentityProvider'
     pod 'AWSDynamoDB'
     pod 'AWSEC2'
     pod 'AWSElasticLoadBalancing'
     pod 'AWSIoT'
     pod 'AWSKinesis'
     pod 'AWSAuthCore'
     pod 'AWSLambda'
     pod 'AWSMachineLearning'
     pod 'AWSMobileAnalytics'
     pod 'AWSS3'
     pod 'AWSSES'
     pod 'AWSSimpleDB'
     pod 'AWSSNS'
     pod 'AWSSQS'
end
